version: "3.9"

services:

  redis:
    image: redis
    ports:
      - "6379:6379"

  worker:
    build:
      context:  .
    hostname: worker
    entrypoint: celery
    command: -A app worker -l info
    links:
      - redis
    depends_on:
      - redis

  flower:
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: -A app flower
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"

  app:
    build: ./
    ports:
      - "8000:8000"
    env_file:
      - .env
#    depends_on:
#      - db