# Generated by Django 5.0.1 on 2024-02-28 10:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ("-dt",),
                "verbose_name": "Заказ",
                "verbose_name_plural": "Список заказов",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("id",),
                "verbose_name": "Продукт",
                "verbose_name_plural": "Список продуктов",
            },
        ),
    ]
